trigger: none
#pipeline kab chalega

pool: alokpool
#pipeline kaha chalega, kis agent me chalega

 
steps:
- script: |
    sudo apt-get update
    sudo apt-get install -y unzip
  displayName: 'Install unzip'
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'
  displayName: terraform install ho raha hai



- task: TerraformTask@5
  
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'alokji'
    backendAzureRmStorageAccountName: 'alokstg'
    backendAzureRmContainerName: 'alokconct'
    backendAzureRmKey: 'xyz'
  displayName: terraform init command chal rahi hai

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'validate'
  displayName: terraform validate command run ho rahi hai
# - task: TerraformTask@5
#   inputs:
#     provider: 'azurerm'
#     command: 'plan'
#     environmentServiceNameAzureRM: 'Demo-Service-Connection'
#   displayName: terraform plan command run ho rahi hai

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'alokji'
    environmentAzureRmOverrideSubscriptionID: 'cba3453a-ff1f-4f51-b6f6-5a1149843776'
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'apply'
    environmentServiceNameAzureRM: 'alokji'
  displayName: terraform apply command run ho rahi hai
